name: react@next integration

on:
  workflow_dispatch:
  schedule:
    # Run every Monday at 12:00 (see https://crontab.guru)
    - cron: '0 12 * * 1'

jobs:
  react-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: .nvmrc
      - run: cat <<< $(jq '.overrides["react"] = "next"' package.json) > package.json
      - run: cat <<< $(jq '.overrides["react-dom"] = "next"' package.json) > package.json
      - run: yarn install --immutable
      # Run the unit tests
      - run: yarn unit
